### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by crystalkalem** [KodyKendall/Auto-Clicker#1]
Why does the program have a direct reference to the system32 file?

**Comment by DefaultO** [comment]
In the code you import these, that's why @crystalkalem .
https://github.com/KodyKendall/Auto-Clicker/blob/5a635c27f9f35dbfb8c42745d207cb758ec2e583/AutoClicker/AutoClicker/AutoClicker.cs#L280

**Comment by KodyKendall** [comment]
Yes, importing Win32 and referencing System32 so we can evoke clicking on windows
