### ISSUE TITLE
Can i modify this for my own autoclicker?

### ISSUE THREAD

**Issue by callmewoem** [KodyKendall/Auto-Clicker#2]
title autoclicker will be private and will not be sold

**Comment by KodyKendall** [comment]
Yes, just curious what are you using it for?

**Comment by Xiliank** [comment]
**_Yo how do i modify dude?_**

**Comment by KodyKendall** [comment]
Hi, What specifically do you want to modify?

**Comment by callmewoem** [comment]
I was planning on using this to learn a bit of c# when it came to stuff like this, and wanted to see if i could improve/modify it. it did help me in c# thank you.

**Comment by KodyKendall** [comment]
Awesome, let me know if you have any questions or suggestions

Thanks

**Comment by Xiliank** [comment]
Oh um ok
